name: check-all

on:
  workflow_dispatch:
#  push:

jobs:
  build-lint:
    uses: ./.github/workflows/lint-test.yaml
    secrets:
      RUSH_BUILD_CACHE_CREDENTIAL: ${{ secrets.RUSH_BUILD_CACHE_CREDENTIAL }}
