name: check-all

on:
  pr:

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  publish:
    needs: [test]
    uses: ./.github/workflows/publish.yaml

  upload-coverage:
    needs: [ test ]
    uses: ./.github/workflows/upload-coverage.yaml
