name: build

on:
  push:
#    paths:
#      - /apps
#      - /libraries
#      - /tools

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js install

      # To run lints and tests we need to ensure all of our dependencies are built first.
      - name: Build all
        run: |
          node common/scripts/install-run-rush.js build -v -p max

      - name: Lint
        run: |
          node common/scripts/install-run-rush.js lint

      - name: Run tests
        run: |
          node common/scripts/install-run-rush.js test --verbose

  deploy-storybook:
    needs: [build-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js install

      - name: Build all
        run: |
          node common/scripts/install-run-rush.js build -v -p max

      - name: Build Storybook
        working-directory: apps/storybook
        run: |
          node $GITHUB_WORKSPACE/common/scripts/install-run-rushx.js build-storybook

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: apps/storybook/storybook-static
          clean: true
