name: storybook

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    paths:
      - /apps/storybook
      - /libraries

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js install

      - name: Build storybook and it's dependencies
        run: |
          node common/scripts/install-run-rush.js build -t @local/storybook -v -p max

      - name: Build Storybook
        working-directory: apps/storybook
        run: |
          node $GITHUB_WORKSPACE/common/scripts/install-run-rushx.js build-storybook

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: apps/storybook/storybook-static
          clean: true
